### ISSUE TITLE
How to use in remote phone

### ISSUE THREAD

**Issue by hailianglone** [openstf/minitouch#12]
Hello
If no use "adb forward",how to use the lib?how to create the socket connection? For java or other Programing language

**Comment by sorccu** [comment]
You can use [adbkit](https://github.com/openstf/adbkit), which is what STF uses. It's only for Node, though. Anyway that's all I can say, we don't provide help with usage, the software and documentation (i.e. README) are provided as-is.

**Comment by hailianglone** [comment]
Thank you for your reply. If can I modify the socket's create method (use ip and port)

**Comment by sorccu** [comment]
You can, but you have to do it on your own. I would not recommend it,
abstract sockets are much easier to use and have fewer edge cases to take
care of.

**Comment by hailianglone** [comment]
Thanks
