### ISSUE TITLE
nc localhost 1111 don't give any output.

### ISSUE THREAD

**Issue by yashasvimakin** [openstf/minitouch#17]
**Problem:**

I tried to follow the steps in Instructions but were not able to figure out where to put commands.
after "nc localhost 1111"  cmd no output Appears.

**Comment by yashasvimakin** [comment]
Its working now thanx.

**Comment by tsreenivash-pk** [comment]
'nc localhost 1111' command is not running for me
Please guide me how to run it

**Comment by sorccu** [comment]
We provide the software and there's a README. No guidance other than that is provided. However, most likely you forgot to do the `adb forward`. Read the README.
