### ISSUE TITLE
about touch resolution

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [openstf/minitouch#19]
As you said in #18
"Screen resolution and touch resolution are often not the same."
Do you know how to get device touch resolution?

**Comment by sorccu** [comment]
With getevent. Or the same thing minitouch already does.

What exactly is the problem you're having on that device?

**Comment by BeiKeJieDeLiuLangMao** [comment]
I have a HTC-one-9,only in this device,miniTouch can't trigger the right point
If i click 1500,1500 for example,miniTouch help me to click 1000,1000

**Comment by sorccu** [comment]
Hmm... I have an HTC One M8 and it works fine. Never tried an M9 though.

Is your device rotated?

**Comment by BeiKeJieDeLiuLangMao** [comment]
no

**Comment by sorccu** [comment]
To be clear, are you using STF or just minitouch?

**Comment by BeiKeJieDeLiuLangMao** [comment]
just miniTouch

**Comment by sorccu** [comment]
Try STF (latest master) and see if it has the same issue. It has various
workarounds that the lower level components are not able to have.

Report back with results.

**Comment by sorccu** [comment]
Also, I just realized that perhaps you're bot mapping the acreen
coordinates to touch coordinates at all. That's what STF does. It retrieves
the native screen size using other components. When you touch, it converts
screen coordinates to touch coordinates. Are you doing that?

**Comment by sorccu** [comment]
That should have been "not mapping" instead of "bot mapping".

**Comment by BeiKeJieDeLiuLangMao** [comment]
I use miniCap to display scene,web page send click position to server like(0.8,0.5), then server use this percent to compute real position like (0.8*1080,0.5*1920)

**Comment by BeiKeJieDeLiuLangMao** [comment]
(0.8x1080,0.5x1920)

**Comment by sorccu** [comment]
So do you map screen coordinates to touch coordinates using both the
dosplay resolution and the touch resolution?

**Comment by BeiKeJieDeLiuLangMao** [comment]
no,i only use scene resolution,i don't know how to get touch resolution so i open this issue

**Comment by sorccu** [comment]
Minitouch tells you the touch resolution. Read the README, especially the
part that covers '^'. It even says that you have to remap it.

**Comment by BeiKeJieDeLiuLangMao** [comment]
Thanks, it's my oversight.
