### ISSUE TITLE
python demo

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minitouch#2]
import socket

BUF_SIZE = 1024
server_addr = ('127.0.0.1', 1111)
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(server_addr)
data = client.recv(BUF_SIZE)
data = '''
d 0 150 150 50\n
c\n
u 0\n
c\n
'''
client.sendall(data)

**Comment by sorccu** [comment]
I'll close this since it's not really an issue :)
