### ISSUE TITLE
how to translate "adb shell input swipe .." into  "m <contact> <x> <y> <pressure>"?

### ISSUE THREAD

**Issue by yangxinQA** [openstf/minitouch#21]
I use adb shell get event -l -t to monitor the swipe action on my android device ,
well a typical drag action is like this:

_[   24969.637831] /dev/input/event4: EV_ABS       ABS_MT_PRESSURE      0000002f            
[   24969.637831] /dev/input/event4: EV_ABS       ABS_MT_POSITION_X    000001bc            
[   24969.637831] /dev/input/event4: EV_ABS       ABS_MT_POSITION_Y    00000370            
[   24969.637831] /dev/input/event4: EV_ABS       ABS_MT_TRACKING_ID   00000000            
[   24969.637831] /dev/input/event4: EV_SYN       SYN_MT_REPORT        00000000            
[   24969.637831] /dev/input/event4: EV_KEY       BTN_TOUCH            DOWN                
[   24969.637831] /dev/input/event4: EV_SYN       SYN_REPORT           00000000            
[   24969.649806] /dev/input/event4: EV_ABS       ABS_MT_PRESSURE      0000002f            
[   24969.649806] /dev/input/event4: EV_ABS       ABS_MT_POSITION_X    000001bc            
[   24969.649806] /dev/input/event4: EV_ABS       ABS_MT_POSITION_Y    00000369            
[   24969.649806] /dev/input/event4: EV_ABS       ABS_MT_TRACKING_ID   00000000_     

  in a" m \<contact\> \<x\> \<y\> \<pressure\> "command , I use 
 ABS_MT_POSITION_X   for the  mintouch "\<x\>"
ABS_MT_POSITION_Y  for the  mintouch "\<y\>"
ABS_MT_PRESSURE for the  mintouch "\<pressure\>"

and ,for the first ABS_MT_POSITION_X  and ABS_MT_POSITION_Y  i use a "d \<contact\> \<x\> \<y\>"command

I translate a drag action as follows:
     _msocket.send(bytes('d 0 489 1420 44\n'))
        msocket.send(bytes('c\n'))
        msocket.send(bytes('m 0 6 -1221 48\n'))
        msocket.send(bytes('c\n'))
        msocket.send(bytes('u 0\n'))
        msocket.send(bytes('c\n'))
        msocket.send(bytes('d 0 124 1388 48'))
        msocket.send(bytes('c\n'))
        msocket.send(bytes('u 0\n'))
        msocket.send(bytes('c\n'))_
Is that right?
or what else should I do for the purpose?

**Comment by sorccu** [comment]
You're missing a newline in `msocket.send(bytes('d 0 124 1388 48'))`. Also, `msocket.send(bytes('m 0 6 -1221 48\n'))` will not work, coordinates are NOT relative. You must provide the absolute coordinate.

**Comment by sorccu** [comment]
Since there's no feedback, I will assume that the question has been solved.
