### ISSUE TITLE
Minitouch is not supported on Android TV

### ISSUE THREAD

**Issue by houshian** [openstf/minitouch#22]
I hava a Nvidia Android TV (sdk version: 24, build: darcy-userdebug 7.0 nrd90m 2427168_956.0090) and I find that minitouch can not run on it. The following is the log of minitouch:

Note: device /dev/input/js1 is not supported by libevdev
Note: device /dev/input/js0 is not supported by libevdev
Note: device /dev/input/mice is not supported by libevdev
Unable to find a suitable touch device

Could you please provide some help? Thanks!

**Comment by sorccu** [comment]
Minitouch only supports multitouch devices. You can try https://github.com/openstf/minitouch/pull/15 for now, but obviously it's not officially supported. If you do try it out, let me know whether it worked or not.
