### ISSUE TITLE
when i run on win7 or win10 it report many socket 10053 error.

### ISSUE THREAD

**Issue by yangxinQA** [openstf/minitouch#23]
when i run on mac it works very well .but on win7 or win10 it reports many socket error the errorno is 10053 . i dont konw why .here is my code ,could you help me ？
def minitouchReplay(cls,cmdlines):
        for cmd in cmdlines:
            cmd = cmd.strip()
            cmd = cmd.replace('\\n','\n')
            cls.msocket.sendall(cmd)
            print "cmd:"+cmd

  cmdlines.append(line)
                    if(line.find('u 0\\n')!=-1):
                        Minitouch.minitouchReplay(cmdlines)
                        cmdlines = []

i cannot findout whats wrong

**Comment by sorccu** [comment]
We don't support Windows, it might work or it might not. We don't want to spend any time on it.

**Comment by yangxinQA** [comment]
ok
