### ISSUE TITLE
minitouch is not supported by 4ktv STB

### ISSUE THREAD

**Issue by ondrj** [openstf/minitouch#27]
Hello,

I have issue with Android set top box 4ktv (manufacturer: 'AMLOGIC', model: '4ktv', version: '6.0.1', abi: 'armeabi-v7a', product: 'p212', cpuPlatform: 'gxl', openGLESVersion: '2.0' ), i tried to apply @LoCorVin   's https://github.com/LoCorVin/minitouch , but it didn't help.

'+ ndk-build
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.    
/root/android-ndk-r16b/build/core/setup-app.mk:81: Android NDK: Application targets deprecated ABI(s): mips64 armeabi mips    
/root/android-ndk-r16b/build/core/setup-app.mk:82: Android NDK: Support for these ABIs will be removed in a future NDK release.    
[arm64-v8a] Install        : minitouch => libs/arm64-v8a/minitouch
[arm64-v8a] Install        : minitouch-nopie => libs/arm64-v8a/minitouch-nopie
[mips64] Install        : minitouch => libs/mips64/minitouch
[mips64] Install        : minitouch-nopie => libs/mips64/minitouch-nopie
[x86_64] Install        : minitouch => libs/x86_64/minitouch
[x86_64] Install        : minitouch-nopie => libs/x86_64/minitouch-nopie
[armeabi] Install        : minitouch => libs/armeabi/minitouch
[armeabi] Install        : minitouch-nopie => libs/armeabi/minitouch-nopie
[armeabi-v7a] Install        : minitouch => libs/armeabi-v7a/minitouch
[armeabi-v7a] Install        : minitouch-nopie => libs/armeabi-v7a/minitouch-nopie
[mips] Install        : minitouch => libs/mips/minitouch
[mips] Install        : minitouch-nopie => libs/mips/minitouch-nopie
[x86] Install        : minitouch => libs/x86/minitouch
[x86] Install        : minitouch-nopie => libs/x86/minitouch-nopie
++ adb shell getprop ro.product.cpu.abi
++ tr -d '\r'
+ abi=armeabi-v7a
++ adb shell getprop ro.build.version.sdk
++ tr -d '\r'
+ sdk=23
+ (( 23 >= 16 ))
+ bin=minitouch
+ adb push libs/armeabi-v7a/minitouch /data/local/tmp/
libs/armeabi-v7a/minitouch: 1 file pushed. 0.4 MB/s (34324 bytes in 0.089s)
+ adb shell /data/local/tmp/minitouch
Note: device /dev/input/mouse1 is not supported by libevdev
Note: device /dev/input/mice is not supported by libevdev
Note: device /dev/input/mouse0 is not supported by libevdev
Unable to find a suitable touch device'

Any idea where could be the problem or how can I fix it?

Many thanks

**Comment by sorccu** [comment]
Only multitouch capable devices are supported right now.

**Comment by ondrj** [comment]
@sorccu Ok, and is there any way to 'turn off' support for input devices in stf?
Because in my case I only work with Android set top boxes and I only need to see graphical (i.e. TV) output, I don't need to remote control them.
I hope you understand me, thanks :)

**Comment by sorccu** [comment]
Unfortunately that's not possible right now, but you might be able to modify the code yourself to do that. You can try commenting out the touch plugin [here](https://github.com/openstf/stf/blob/badb3ed3be5d1b5cf889ad61244c3ca1a4fc6de5/lib/units/device/index.js#L31), but I'm not sure if that's all you need to do.

**Comment by ondrj** [comment]
Ok, thanks a lot @sorccu , I will give it a try :+1:

**Comment by nateby** [comment]
@ondrej23 
Hi
I run stf on set top box too.
Did you comment out the touch plugin code? it works?
Thanks

**Comment by ondrj** [comment]
Hey,
commenting out did not work but, we have found a solution, but it was workaround.
Which version of Linux kernel ( <code>uname -a</code> ) do you use on your STB device?

**Comment by ondrj** [comment]
Hey @nateby do you really want to help with this issues? I'm ready to help you, I just got to know version of Linux kernel on your Set Top Box device (check it via adb shell and <code>uname -a</code>)

**Comment by ondrj** [comment]
Ok, I'm closing this one; I have found workaround for one particular version of Linux kernel, so feel free to message me in case of any issue.

**Comment by sorccu** [comment]
Would be useful to know what it was :)

**Comment by ondrj** [comment]
I have compiled custom Linux kernel module called virtual_touchscreen.so, that can emulate virtual display for devices like set top boxes. I'll push it with description to my public repos later.

**Comment by ondrj** [comment]
Hey, here it is:
https://github.com/ondrej23/Virtual_Touchscreen_kernel_module
Feel free to use it for your purpose if you have same version of Linux kernel. It will emulate virtual display on devices with no display (e.g. set top boxes).

**Comment by egpriest** [comment]
ondrej23 - is the source code available for the Virtual_Touchscreen_kernel_module or can the steps required to create a custom virtual_touchscreen for kernel version 3.18.x be provide
