### ISSUE TITLE
when excute "ndk-build" some folder do not generate

### ISSUE THREAD

**Issue by ghost** [openstf/minitouch#33]
Hi, sorccu. sorry to bother you.
     After excute "ndk-build" command line, in the folder "lib",I find 4 folders which are "arm64-v8a","armeabi-v7a","x86","x86_64" . But the "armeabi","mips","mips64" folder do not generate. I can't find the reason, so ask you for help. Thank you for your precious time.
     My compute information:
     System Type:               x64-based PC
      Processor(s):              1 Processor(s) Installed. [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel 
                                         ~3408 Mhz

**Comment by koral--** [comment]
It seems that you are using NDK r17 or newer. Support for those 3 platforms was dropped since r17: https://github.com/android-ndk/ndk/wiki/Changelog-r17#announcements

**Comment by sorccu** [comment]
Good catch @koral-- 👍
