### ISSUE TITLE
Samsung s8 work not well

### ISSUE THREAD

**Issue by yaofangwx123** [openstf/minitouch#34]
First I thank for your minitouch very much,it really useful to me!Now,I have a 
Android phone Samsung s8,I use the same style send the position to the device,
But it not work well,other android devices are ok,I cannot find the problem,so if you can help me,please give me some help or some advice,thank you

**Comment by yaofangwx123** [comment]
I send the position x = 100,y = 100,but the Samsung s8 show the click position is x = 26.3 y = 54.2

**Comment by sorccu** [comment]
You have to retrieve the screen size externally and map coordinates from the screen coordinate space to the touch coordinate space. The touch device usually has a different size.

**Comment by yaofangwx123** [comment]
OK.Thanks!I will try later!

**Comment by yaofangwx123** [comment]
oh!Thank you very much!I solve my problem by retrieve the screen size!best wish to you!
