### ISSUE TITLE
wait in your own code

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minitouch#4]
What's the content in the <> means, could you give me some examples?

Long tap on (10, 10) with 50 pressure using a single contact.

d 0 10 10 50
c
<wait in your own code>
u 0
c

**Comment by sorccu** [comment]
Something like `sleep()`.

**Comment by likezjuisee** [comment]
Can minitouch in android phone recognize the sleep code?

**Comment by sorccu** [comment]
No! I don't know Python very well, but the idea is to do something like this:

``` python
client.sendall("d 0 150 150 50\n")
client.sendall("c\n")
sleep(2)
client.sendall("u 0\n")
client.sendall("c\n")
```
