### ISSUE TITLE
Big Problem!

### ISSUE THREAD

**Issue by ZENGYANYAN** [openstf/minitouch#5]
WHAT A GREAT JOB！
But I find a small problem . 
when i use the adb command ,"input keyevent XXX"，it too slow .
so i want have a function call "minikey" that can input keyevent faster !
poor english , sorry ......
thanks for your coding!

**Comment by sorccu** [comment]
I think Appium has something for that. Not 100% sure though.

**Comment by ZENGYANYAN** [comment]
thanks your answer !

**Comment by BeancurdPachelbel** [comment]
Do you solve the problem the input rate of the  keyboard?,It's too slow to input by adb command!

**Comment by sorccu** [comment]
Just try STF, if it's fast enough for you then I guess we did. If not then
we didn't.

**Comment by BeancurdPachelbel** [comment]
I tried stf long time ago,but I couldn't feel the input rate is enough for testing android  mobile.There is nothing could be better than your project ,minicap,I hope I could learn more form you.
