### ISSUE TITLE
How home、back、menu key work?

### ISSUE THREAD

**Issue by willysys** [openstf/minitouch#7]
In minitouch can parse command like 'm <contact> <x> <y> <pressure>', but how home、 back、menu key work？ I don't find any code in minitouch.c to handle those event.  Those key event only can be handled by libevdev?
Thanks for your help.

**Comment by sorccu** [comment]
Minitouch is for touch events only. Keys are provided by STFService.apk.

**Comment by willysys** [comment]
Thanks for you answer. 
But how does STFService.apk make keys work?  Does STFService.apk install in phone?
Thanks for your help.

**Comment by sorccu** [comment]
Look at the source code and/or check how stf is using it.

You can also use 'adb shell input keyevent' if you don't care about latency
too much.

**Comment by willysys** [comment]
ok ,Thank you very much.
