### ISSUE TITLE
Unable to do git submodule update 

### ISSUE THREAD

**Issue by yashasvimakin** [openstf/minitouch#8]
fatal: unable to connect to anongit.freedesktop.org:
anongit.freedesktop.org[0: 131.252.210.161]: errno=Operation timed out

Thanks in Advance.

**Comment by monkeyDledger** [comment]
I changed the url in file .gitmodules：
[submodule "libevdev"]
	path = jni/vendor/libevdev/source
	url = **https://github.com/whot/libevdev.git**

**Comment by monkeyDledger** [comment]
@yashasvimakin 
I changed the url in file .gitmodules：
[submodule "libevdev"]
path = jni/vendor/libevdev/source
url = https://github.com/whot/libevdev.git
 then it works

**Comment by yashasvimakin** [comment]
Hi @monkeyDledger 

Still same issue. :(

**Comment by sorccu** [comment]
It works fine for me. Sounds like a network (possibly firewall) issue.

**Comment by yashasvimakin** [comment]
Will try again in different network then. thanks @sorccu , is there any node js sample app for both minicap and minitouch together as STF is too much of load? 

Thanks in advance.

**Comment by sorccu** [comment]
No, but there's something in the ios-minicap repo for minicap.

You know I actually wrote it all. Surely you have time to at least figure
out how to use them since you already know they work :)

**Comment by yashasvimakin** [comment]
Sure @sorccu ,will try to make this work then.

**Comment by Quad-Plex** [comment]
I was having the same issue however I did not want to use some mirror from 2018, just changing the url to `url = https://gitlab.freedesktop.org/libevdev/libevdev.git` is a better fix imo
